# bernoulli's distribution

In [60]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

In [10]:
def bernoulli(x,p):
    if x==1:
        return p
    elif x==0:
        return 1-p
    else:
        return 0
print(bernoulli(0,0.6))
print(bernoulli(1,0.6))

0.4
0.6


In [22]:
np.mean(bernoulli(1,0.6))

0.6

In [31]:
np.var(bernoulli(0,0.6))

0.0

In [47]:
p=0.6
samples=bernoulli.rvs(p,size=10)
print(samples)

[0 1 1 1 0 1 1 0 1 0]


In [57]:
bernoulli.cdf(1,p)

1.0

# binomial distribution

In [78]:
from scipy.stats import binom

n=10
p=0.6

samples=binom.rvs(n,p,size=10)
print(samples)  # in 1st exp no of success is 5

[5 5 4 5 7 7 8 7 8 8]


In [80]:
s=binom.pmf(4,n,p)
print(s)   # 11 % of chance for no of success 4

0.11147673600000009


# poisson distribution

In [91]:
from scipy.stats import poisson
mu=3

samples=poisson.rvs(mu,size=10)
print(samples)

[1 2 4 2 3 3 5 5 2 3]


In [95]:
a=poisson.pmf(4,mu)
print(a)

0.16803135574154085


# multinomial 

In [122]:
from scipy.stats import multinomial
n=10
pval=[0.6,0.3] # prob of outcomes
print(multinomial.rvs(n,pval,size=5))
print(multinomial.pmf([5,3],2,pval))

[[6 4]
 [7 3]
 [5 5]
 [5 5]
 [8 2]]
0.0
